### ISSUE TITLE
[ERROR] java.io.FileNotFoundException: https://picasaweb.google.com/data/feed/api/user/default/albumid/default

### ISSUE THREAD

**Issue by nevixa** [Bostwickenator/FtpPhotosUploader#1]
Hi,

First of all, sorry to post this issue here , in the wrong project because it is about STG Uploader, but I couldn't find a better place to contact you. Second: I would love to help fix this bug and make this app even better. I have tons of experience with Android app development. 

So when do I get the error:
Since it happened, it happens every time I try to upload again. So now uploading never works (anymore). It worked the first few times, but at a certain point it stopped working. This is what I see/do:
- start app
- see it connecting to wifi
- see the user interface with the two buttons Start Upload and Settings. I also see that 100 photos are ready to upload.
- When I click Start Upload it tries to start upload, and I see the 'small animation', but it does not upload and after a while it just stops.

The logs says:
[INFO] setting wifi enabled state to true
[INFO] Resume org.bostwickenator.googlephotos.LoginActivity
[INFO] Pause org.bostwickenator.googlephotos.LoginActivity
[INFO] Resume org.bostwickenator.googlephotos.MainActivity
[INFO] Response Code : 403
[ERROR] java.io.FileNotFoundException: https://picasaweb.google.com/data/feed/api/user/default/albumid/default
[INFO] Response Code : 403
[ERROR] java.io.FileNotFoundException: https://picasaweb.google.com/data/feed/api/user/default/albumid/default
[INFO] Response Code : 403

What doesn't work:
- Clearing the database
- Re authorizing Google

What does work (strangely enough):
- Installing the app again (without removing it first)

**Comment by Bostwickenator** [comment]
https://github.com/Bostwickenator/STGUploader/issues/5

**Comment by zoltanf** [comment]
Hello. First of all, thank you for this project. 

Any updates on this issue? 
I'm also getting sometimes this [ERROR] java.io.FileNotFoundException, in the logs, on Sony A6000.
Usually it happens after a large number of images upload. It goes away after some time (like a day).
