### ISSUE TITLE
FTP_Uploader_1970_01_01

### ISSUE THREAD

**Issue by TothCsanad** [Bostwickenator/FtpPhotosUploader#4]
Hi,
Querying the date may have a problem because the created folder is: FTP_Uploader_1970_01_01
Please fix it if possible! Thanks :-)

**Comment by Deph0** [comment]
Hi, Please make sure your device has the correct time and date.

**Comment by TothCsanad** [comment]
The date is set correctly. I can not even set an unrealistic date. The camera's language is set to Hungarian. I don't know if it affects...

**Comment by TothCsanad** [comment]
I just noticed that ADB shell date query returns 1970. In the camera settings, the date is set correctly and photos are also dated. The two dates are not synchronized.

**Comment by Deph0** [comment]
Odd, have you tried to set the time yet again in the menus?

Since you mention you've established a ADB connection, it may be an idea to try set datetime thu ADB Shell, using for ex. [these instructions](https://www.codeday.top/2017/07/28/31323.html) *(untested by me).

Another idea would be to connect the camera to your home wifi and see if it syncs the system date/time thu the internet (ntp).

I should probably note that I am unaffiliated with this project, I'm just trying to be helpful.

**Comment by mainpart** [comment]
> I just noticed that ADB shell date query returns 1970. In the camera settings, the date is set correctly and photos are also dated. The two dates are not synchronized.

was that useful? setting a datetime in adb?

**Comment by axelrathey** [comment]
I have the sam problem. Date an time in the cam menu is current. How to set date an time in adb shell?
thanks Axel

**Comment by isLaLa** [comment]
I don't understand English and I don't know how to write Android programs. I copied a piece of code related to getting the time from PMCADemo into this program and surprisingly fixed the 1970_01_01 error during compilation. The following is the modified code   

        protected Void doInBackground(Void... params) {
            Calendar calendar = getDateTime().getCurrentTime();
            //String date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(calendar.getTime());
            String date = new SimpleDateFormat("yyyy-MM-dd").format(calendar.getTime());
            int timeZoneOffset = calendar.getTimeZone().getRawOffset() / 1000 / 3600;
            String camera_time = (date + " (GMT" + (timeZoneOffset >= 0 ? "+" : "") + timeZoneOffset + ":00)");

            try {
                FtpClient ftp = new FtpClient();
                ftp.connect();

                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        textViewUploadStatus.setText(R.string.statusUploading);
                    }
                });

                if (settingsStore().getBoolean(SETTING_CREATE_ALBUM, true)) {
                    //String albumName = "FTP_Uploader_" + getDate();
                    String albumName = "FTP_Uploader_" + camera_time;

**Comment by Bostwickenator** [comment]
Applied calendar suggestion on main

**Comment by axelrathey** [comment]
Hi Bostwickenator,

I would like you to make a new release of ftp_uploader with the above calendar changes.

Thanks a lot 
Axel
